version: "3"

services:
  aws_sync:
    build: ./aws_sync
    container_name: aws_sync
    volumes:
      - counterdata:/app/db
    env_file:
      - .env
    network_mode: host

  counter:
    build: ./counter_server
    container_name: counter_server
    volumes:
      - counterdata:/app/db
    env_file:
      - .env
    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    env_file:
      - .env
    restart: always
    network_mode: host

volumes:
  counterdata:
    driver: local
